### ISSUE TITLE
Widget not fluid

### ISSUE THREAD

**Issue by ghazpar** [romanvm/django-tinymce4-lite#11]
Hi,

By default, the admin widget width is hardcoded to 1024. Is there a way to make it fluid with regards to the width of the browser tab?

Best.

**Comment by ghazpar** [comment]
Just find out that the widget can become fluid simply by setting ` 'width': 'auto'` in the config dict.

**Comment by romanvm** [comment]
With `auto` width the widget was stretched beyond the browser window in Django 1.11 admin, so I set the fixed width. I glad that you have sorted this out.

**Comment by ghazpar** [comment]
No, I'm running django 1.11.1 and the widget does NOT stretch pass the browser tab. However, It does have a minimum width (~710px), so if you have a narrow window, than it will stretch pass the border, but your default will stretch even more...
