### ISSUE TITLE
Customize toolbar

### ISSUE THREAD

**Issue by gusarg81** [romanvm/django-tinymce4-lite#15]
Hi,

I am testing the latest stable version of django-tinymce4-lite (switched from django-ckeditor because is not working on ajax calls) and I wonder if there is a way to customize the toolbar in settings.py (like django-ckeditor) or another place.

django-tinymce4-lite: v1.4.2
django: v1.11.4

Thanks in advance.

**Comment by gusarg81** [comment]
Ok, nevermind i just figured it out by reading the source code that you can do it with TINYMCE_DEFAULT_CONFIG inside settings.py (is this on the docs? Because I didn't find it).

**Comment by romanvm** [comment]
> is this on the docs? Because I didn't find it

"Configuration" section name might have given you a hint: http://romanvm.github.io/django-tinymce4-lite/configuration.html#configuration

**Comment by gusarg81** [comment]
Ops, sorry. Missed that one. There is no need  to be rude :) Thanks a lot!
