### ISSUE TITLE
ValueError when running Django management commands with ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by romanvm** [romanvm/django-tinymce4-lite#17]
When `ManifestStaticFilesStorage` is used as a storage class for static files, running <s>`collectstatic`</s> any Django management command with `DEBUG = False` causes `ValueError` exception because `staticfiles_storage.url()` tries to get hash-versioned filename from `manifest.json` that is not there yet. Current workaround is to temporarily switch to `DEBUG = True` and run `collectstatic` but it is not a good idea to manipulate with `DEBUG` in production. A solution is needed that both allows to run `collectstatic` with `DEBUG = False` and retains serving hash-versioned static assets from `tinymce4-lite`.

**Comment by AlJohri** [comment]
@romanvm This fix unfortunately isn't completely working for me.

```python
if JS_URL is None:
    # Ugly hack that allows to run collectstatic command with ManifestStaticFilesStorage
    _orig_debug = settings.DEBUG
    if 'collectstatic' in sys.argv:
        settings.DEBUG = True
    JS_URL = staticfiles_storage.url('tinymce/js/tinymce/tinymce.min.js')
    settings.DEBUG = _orig_debug
```

I have a bunch of other commands using production environment variables, but locally. For example, my script to refresh the database now fails:

```
#!/bin/sh

set -e

envdir envs/prod pipenv run django-admin pg_dump && \
envdir envs/local pipenv run django-admin dropdb --noinput # allow dropdb to fail locally

envdir envs/local pipenv run django-admin createdb --noinput && \
envdir envs/local pipenv run django-admin pg_restore && \
envdir envs/local pipenv run django-admin migrate # runs local migrations on top of last version of prod db
```

The `envdir envs/prod pipenv run django-admin pg_dump` command fails.

**Comment by romanvm** [comment]
Is this the same issue with `ValueError` and `ManifestStaticFilesStorage`?

**Comment by AlJohri** [comment]
@romanvm yeah, I get the ValueError since `'collectstatic' in sys.argv` doesn't apply. I'm running a different command so `collectstatic` isn't in the sys.argv. Seems like the code gets run on import.

**Comment by romanvm** [comment]
I suspected that it may not work with other management commands that import the whole Django project. Currently I don't have an acceptable solution so any help is appreciated.

Is there any specific reason why you are using `ManifestStaticFilesStorage`. Maybe the default file storage class will be enough?
