### ISSUE TITLE
Problem installing 1.5.2 tar.gz: missing changelog.rst

### ISSUE THREAD

**Issue by rvanlaar** [romanvm/django-tinymce4-lite#21]
Hi,

I'm installing django-tinymce4-lite and am getting the following error:

> error: [Errno 2] No such file or directory: '/tmp/easy_install-fntzp9h3/django-tinymce4-lite-1.5.2/docs/changelog.rst'
> An error occurred when trying to install /tmp/tmp68dxjptnget_dist/django-tinymce4-lite-1.5.2.tar.gz. Look above this message for any errors that were output by easy_install.
> While:
>   Installing python.
>   Getting distribution for 'django-tinymce4-lite'.

Due to the following code in setup.py:
https://github.com/romanvm/django-tinymce4-lite/blob/94982b03e2a788056674ac59e45b524d9381d26e/setup.py#L19

The docs directory is missing from the .tar.gz.

**Comment by rvanlaar** [comment]
The wheel installs fine.

**Comment by romanvm** [comment]
I will look into it

**Comment by rvanlaar** [comment]
Allright :+1:
