### ISSUE TITLE
package fails to upgrade to 1.8.0 in Django 1.11.8

### ISSUE THREAD

**Issue by Pantzan** [romanvm/django-tinymce4-lite#25]
Hi guys, not sure if is bug or not but I think it should be mentioned. Pip complains to upgrade the package from 1.6.0 or 1.7.0 to 1.8.0 in Python 2.7 and the latest Django version for that, 1.11.8.
Pip is using the latest version of Django that has in the pool which is 2.0 as cached and thus fails the upgrade.
To solve the issue I needed to manually install the package without upgrade
`pip install django-tinymce4-lite==1.7.0`
Here is the error report

```
pip install django-tinymce4-lite -U
Collecting Django>=1.8.0 (from django-tinymce4-lite)
  Using cached Django-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cN4rKg/Django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
```

**Comment by romanvm** [comment]
Don't ever use `--upgrade` option with `pip install` unless you absolutely sure that your package has no dependencies, because `--upgrade` blindly upgrades all dependencies with a strong chance that it breaks your application.
