### ISSUE TITLE
File browser breaks in production

### ISSUE THREAD

**Issue by ghost** [romanvm/django-tinymce4-lite#26]
Not sure if this is a bug, but I can't find anything about this anywhere. When using django-tinymce4-lite in combination with django-filebrowser-no-grappelli, everything seems to work great locally. In production, however, I get the following console error (in tinymce.min.js) upon trying to upload a new image in the insert/edit image modal:

`Mixed Content: The page at 'https://...38/change/' was loaded over HTTPS, but requested an insecure resource 'http://localhost/admin/filebrowser/browse/?pop=4&type=image'. This request has been blocked; the content must be served over HTTPS.`

TinyMCE seems to try to load the filebrowser from localhost? Did I miss a setting?

**Comment by romanvm** [comment]
I'd recommend to check your project's configuration, including that of the filebrowser application. `tinymce4-lite` does not use absolute or hardcoded URLs anywhere. The URL in question is constructed with Django's `reverse`: https://github.com/romanvm/django-tinymce4-lite/blob/master/tinymce/views.py#L121-L128

**Comment by ghost** [comment]
In the end, it comes down to a call to build_absolute_uri(), which in turns requests self.gethost() to build the URL. This (on my production environment) returns "localhost" instead of the base URL. If this is unexpected behaviour, I guess I'll have to make some changes in my setup. Thanks for the quick reply!

**Comment by ghost** [comment]
To wrap this up, the problem indeed was that my production server returned 'localhost' on request.get_host() which it shouldn't have. Thanks for the help!
