### ISSUE TITLE
NoReverseMatch at /admin/socnotes/mymodel/add/

### ISSUE THREAD

**Issue by csulit** [romanvm/django-tinymce4-lite#27]
![image](https://user-images.githubusercontent.com/31933946/35378122-a0fd1fa6-01ec-11e8-8399-26d89c9ff33f.png)

and this is what i get if i click 'add my model'

![image](https://user-images.githubusercontent.com/31933946/35378154-c79924e8-01ec-11e8-9b28-6bf5c0685e38.png)

i also change tinycme urls.py url to path

![image](https://user-images.githubusercontent.com/31933946/35378183-e17d8b42-01ec-11e8-8b2d-30b847963eb0.png)

this is my model.py

![image](https://user-images.githubusercontent.com/31933946/35378205-f0ef0da8-01ec-11e8-9cf6-7863f0612d07.png)

**Comment by romanvm** [comment]
Check if you have configured `tinymce4-lite` according to the documentation.

Also I need to note that `tinymce4-lite` is compatible with Django 2.0 as it is. You are free to modify its code according to the license terms, but it is your sole responsibility to support the modified code.

**Comment by csulit** [comment]
Yes i follow your documentation  properly.

**Comment by romanvm** [comment]
Then I cannot help you. The usual suspect in such cases is misconfigured `urls.py` of your Django project, but since you made changes to this package's code, there's not much I can do. I can provide limited support only for the code hosted in this repository as it is.

**Comment by csulit** [comment]
Okay thanks for that.
