### ISSUE TITLE
Auto resize

### ISSUE THREAD

**Issue by arviesan24** [romanvm/django-tinymce4-lite#30]
I can't find a way to auto resize the width of the text area in the form. I was able to fit it to the form but it will ruin the design for devices with smaller screen.

**Comment by romanvm** [comment]
TinyMCE supports `'auto'` property for width and height to auto-resize it to the size of the external container.

**Comment by arviesan24** [comment]
thanks. it works now.
I changed this in the forms.py file

`mce_attrs={'required': True, 'width': 'auto'}`

**Comment by arviesan24** [comment]
I tried this in the settings.py:

`TINYMCE_DEFAULT_CONFIG = {
    'height': 'auto',
    'width': 'auto',
}`

but still nothing happened.
