### ISSUE TITLE
Type error n is not a function.

### ISSUE THREAD

**Issue by gohanko** [romanvm/django-tinymce4-lite#34]
When I installed django-tinymce4-lite with filebrowser no grapelli, it returns Type error n is not a function.

You can check out the project here

https://github.com/YiiKuoChong/yiikuochong-site

```http://127.0.0.1:8000/static/tinymce/js/tinymce/themes/modern/theme.min.js:1:98208
zm/c.fire
http://127.0.0.1:8000/static/tinymce/js/tinymce/tinymce.min.js:2:182881
fire
http://127.0.0.1:8000/static/tinymce/js/tinymce/themes/modern/theme.min.js:1:31285
init/<
http://127.0.0.1:8000/static/tinymce/js/tinymce/themes/modern/theme.min.js:1:70370
zm/c.fire
http://127.0.0.1:8000/static/tinymce/js/tinymce/tinymce.min.js:2:182881
fire
http://127.0.0.1:8000/static/tinymce/js/tinymce/themes/modern/theme.min.js:1:31285
o
http://127.0.0.1:8000/static/tinymce/js/tinymce/themes/modern/theme.min.js:1:35500
C
http://127.0.0.1:8000/static/tinymce/js/tinymce/tinymce.min.js:2:12511
d
http://127.0.0.1:8000/static/tinymce/js/tinymce/tinymce.min.js:2:12662```

**Comment by romanvm** [comment]
I have no idea what all this means.

**Comment by gohanko** [comment]
well I installed django-tinymce4-lite and file browser as the instruction said and it returns this error where the filebrowser didnt work so I thought it might be one of your javascript. I'll recheck my code again tommorow, the lack of any clue for the error is going to be a pain.

**Comment by romanvm** [comment]
It looks like the error is thrown somewhere inside minified TinyMCE JS files. They are outside of my control.    Make sure you are using a modern browser.

**Comment by gohanko** [comment]
Yes, I am running the latest version of Firefox. Wierd thing is that it returns this error everytime I press the file browse button when inserting a file. It is not opening either but it seems to be only my project.

**Comment by gohanko** [comment]
Since I am here, I'll take the opportunity to ask you, what does this line of code do?

``` USE_FILEBROWSER = getattr(settings, 'TINYMCE_FILEBROWSER', 'filebrowser' in settings.INSTALLED_APPS)```

I noticed that using HTMLField() works like a charm but when I use it through an admin interface to load the js file, the filebrowser doesn't work so I am trying to study how the app work.

**Comment by romanvm** [comment]
This line of code determines if the filebrowser application is to be used depending on your Django project configuration.

**Comment by gohanko** [comment]
Closed because this is not a package error but programming error. I tried to enrich the admin page manually of a third party app but the best way to do it is by adding a widget for the specific field
