### ISSUE TITLE
Admin shows old tinymc

### ISSUE THREAD

**Issue by milossh** [romanvm/django-tinymce4-lite#39]
Hello.

I've first installed django-tinymce package with pip, for my django, configured it, and it worked properly. Then I figured it's missing paragraphs UI, and found out about django-tinymce4-lite package. Now, since you're using the same `tinymce` module name, I simply uninstalled django-tinymce, and installed django-tinymce4-lite with pip, restarted servers(both gunicorn and nginx), ran collectstatic, and I'm still getting the old version of tinymce.

What could I be doing wrong?

**Comment by romanvm** [comment]
Cache problems? Do a full page reload in your browser (ctrl+F5 in FF, shift+F5 in Chrome) and invalidate caches in the middle (proxy, Varnish, etc.), if any.

**Comment by thirdmusketeer** [comment]
Hello,
This is not related to current issue.
i want to fix font style, size and color for the text. is there any way.

when pasting into the editor, whatever styles might be, all content should be converted to fixed styles.

**Comment by milossh** [comment]
@romanvm  Sorry, I somehow missed this reply. This said, I've tried even removing and adding it back again, hard refresh browser, changed browser, nothing helped. I also don't use any caching server side like varnish/proxy/redis...

**Comment by romanvm** [comment]
@thirdmusketeer It is very rude to hijack somebody else's issue ticket. Please do not post anything here.

@milossh Another possibility I can think of is that you have forgotten to activate your virtual environment before running pip and installed this package into your system or user site-packages.

**Comment by milossh** [comment]
@romanvm thanks for your response. Now, here's my console:

```
milos@ubuntu-4gb-nbg1-1:~/django-doktorino/doktorinosite$ deactivate
milos@ubuntu-4gb-nbg1-1:~/django-doktorino/doktorinosite$ pip show tinymce
milos@ubuntu-4gb-nbg1-1:~/django-doktorino/doktorinosite$ pip show django-tinymce
milos@ubuntu-4gb-nbg1-1:~/django-doktorino/doktorinosite$ source ../env/bin/activate
(env) milos@ubuntu-4gb-nbg1-1:~/django-doktorino/doktorinosite$ pip show django-tinymce
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env) milos@ubuntu-4gb-nbg1-1:~/django-doktorino/doktorinosite$ pip show django-tinymce4-lite
Name: django-tinymce4-lite
Version: 1.7.1
Summary: A Django application that provides a fully functional TinyMCE 4 editor widget for models and forms.
Home-page: https://github.com/romanvm/django-tinymce4-lite
Author: Roman Miroshnychenko (fork author)
Author-email: roman1972@gmail.com
License: MIT License
Location: /home/milos/django-doktorino/env/lib/python3.5/site-packages
Requires: jsmin, Django
Required-by:
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env) milos@ubuntu-4gb-nbg1-1:~/django-doktorino/doktorinosite$
```

**Comment by romanvm** [comment]
Then I'm out of ides. Even with aggressive caching it should not happen because `tiymmce4-lite` uses different names for static files. Please do the following thing:

* Post a screenshot here with your issue.
* Press `ctrl+U` to show the source of your rendered admin page and post it to some pastebin site and provide a link here. If the admin page contains confidential info, then please post only the part containing `<link rel="stylesheet">` and `<script>` tags. I'd like to see all those tags.
* Open a developer console in your browser and see if there are any error messages there.

**Comment by romanvm** [comment]
I'm closing this issue since there has been no follow-up.
