### ISSUE TITLE
language file fr.js missing

### ISSUE THREAD

**Issue by issue2k** [romanvm/django-tinymce4-lite#4]
Hello, the language file resolving does not work well for us when changing django language to french ('fr').

```
  Failed to load: http://localhost:8000/static/tinymce/js/tinymce/langs/fr.js
```

What exists in the codebase is fr_FR.js but from code i think this will never be resolved or is there any configuration parameter that i missed?

Language config from settings:

```
  LANGUAGE_CODE = 'en' 
  LANGUAGES = [
      ('en', _('English')),
      ('fr', _('French')),
      ('de', _('German')),
  ]
```

My TinyMCE default config:

```
TINYMCE_DEFAULT_CONFIG = {
    'selector': 'textarea',
    'theme': 'modern',
    'plugins': 'link image preview codesample contextmenu table code',
    'toolbar1': 'bold italic underline | alignleft aligncenter alignright alignjustify '
                '| bullist numlist | outdent indent | table | link | codesample | preview code',
    'contextmenu': 'formats | link',
    'menubar': False,
    'inline': False,
    'statusbar': True,
    'height': 360,
}
```

Thanks much!

**Comment by romanvm** [comment]
For French TinyMCE uses full "language_COUNTRY" codes: `fr_FR` and `fr_CH`. You can either use a full language code in Django: `fr-fr` or override automatic language configuration by specifying respective [TinyMCE language](https://www.tinymce.com/docs/configure/localization/) options explicitly in `TINYMCE_DEFAULT_CONFIG`. Or you can manually rename `fr_FR.js` to `fr.js`.

**Comment by issue2k** [comment]
Great thank you for responding that fast and providing a solution 👍 , i selected to put a fr.js file into the projects static folder but your first solution sounds better, depending on the side effects, will give it a try.
