### ISSUE TITLE
Not working in Widget

### ISSUE THREAD

**Issue by bwilliams18** [romanvm/django-tinymce4-lite#42]
Hey! Trying to get this to work through the widget decleration on a form field and it's not rendering at all. Any advice on how to resolve?

**Comment by romanvm** [comment]
> Any advice on how to resolve?

Unfortunately, your issue ticket has zero information that might help to diagnose the issue. Please read the [contribution guide](https://github.com/romanvm/django-tinymce4-lite/blob/master/CONTRIBUTING.md) about what information is needed.

**Comment by romanvm** [comment]
I'm closing this issue since there is no follow-up.
