### ISSUE TITLE
embed social media

### ISSUE THREAD

**Issue by CARocha** [romanvm/django-tinymce4-lite#43]
Is posible embed code social media? like (twitter, facebook, instagram) how to?
i used insert media, embed and paste code but no working in front page no show correctly

i try other way is put de code in <source code> but again no show correctly 

<img width="618" alt="captura de pantalla 2018-11-05 a la s 14 23 36" src="https://user-images.githubusercontent.com/168115/48024630-ca024580-e106-11e8-92be-97a9e29cb811.png">

any help or way to put embed code? from social media.
Thank

**Comment by romanvm** [comment]
Your question is not about this Django application and you should address it to TinyMCE support. AFAIK, they provide a premium plugin with this functionality.
