### ISSUE TITLE
The big problem for productiong with fu*ked strings

### ISSUE THREAD

**Issue by ZaArsProgger** [romanvm/django-tinymce4-lite#44]
Dear developers. U wrote two string, whose break down app in production on 32bit machine. Why u override logger config? Config must override in settings.py, and not in widgets.py and views.py. Proggrammer what wrote this, is bad guy. Im tired

**Comment by romanvm** [comment]
Care to elaborate?

**Comment by ZaArsProgger** [comment]
Yep
