### ISSUE TITLE
how can i change color of text area in django-tinymce-4-lite?

### ISSUE THREAD

**Issue by theaterwinner** [romanvm/django-tinymce4-lite#46]
how can i change color of text area in django-tinymce-4-lite?

i have tiny-mice options in my setting.py file

TINYMCE_DEFAULT_CONFIG = {
    # 'width': "auto",
    # 'height': "500",
    # 'selector': "textarea",
    # 'theme': "modern",
    # 'paste_data_images': True,
    # 'plugins': [
    #     "advlist autolink lists link image charmap print preview hr anchor pagebreak",
    #     "searchreplace wordcount visualblocks visualchars code fullscreen",
    #     "insertdatetime media nonbreaking save table contextmenu directionality",
    #     "emoticons template paste textcolor colorpicker textpattern"
    # ],
    # 'toolbar1': "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    # 'toolbar2': "print preview media | forecolor backcolor emoticons",
    # 'image_advtab': True,

    'width': "auto",
    'height': "350",
    'selector': "textarea",
    'theme': "modern",
    'paste_data_images': True,
    'plugins': [
        "advlist autolink lists link  charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
    ],
    'toolbar1': "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link ",
    'toolbar2': "print preview media | forecolor backcolor emoticons",
    'image_advtab': True,

}

thanks

**Comment by romanvm** [comment]
I guess you need to apply some custom CSS styles or a theme. I'd recommend to ask this question on TinyMCE support forums because it is outside of scope of this Django application.

**Comment by romanvm** [comment]
I'm closing this issue because it's not really related to this project.
