### ISSUE TITLE
How to add custom classes to specific elements?

### ISSUE THREAD

**Issue by sometimescool22** [romanvm/django-tinymce4-lite#48]
Hey, say I want to add the class `browser-default` to all `ul` elements. How would I do that? I am just using `    content = HTMLField('Content')` in my models.py.

**Comment by romanvm** [comment]
I'm afraid this question is outside the scope of this project and should be done with JavaScript in TinyMCE itself, probably via editor events. Please read TinyMCE 4 docs about that: https://www.tiny.cloud/docs-4x/advanced/events/

**Comment by sometimescool22** [comment]
Ok, thanks.
