### ISSUE TITLE
Getting the correct language for tinymce

### ISSUE THREAD

**Issue by Gagaro** [romanvm/django-tinymce4-lite#5]
Hi,

Is there a reason why the language is truncated in `get_language_config` (https://github.com/romanvm/django-tinymce4-lite/blob/master/tinymce/widgets.py#L41) rather than passed through `convert_language_code`?

For example, for `fr-fr`, I should get `fr_FR` and not `fr`. The workarounds I currently have is to set the language settings in `TINYMCE_DEFAULT_CONFIG`, but that shouldn't be needed (even more if I want to have a multilingual app).

Thanks

**Comment by romanvm** [comment]
Most TinyMCE4 localization files do not use country codes, so passing a full language code will break localization for those languages. I'm aware of the problem with French but haven't thought of a reliable solution for that, except for explicitly setting a language in the widget config. Maybe an additional configuration parameter with custom language mapping? Something like that:
```python
TINYMCE_CUSTOM_LANG_MAPPING = {'fr': 'fr_FR'}
```

**Comment by Gagaro** [comment]
It would still not work if we have `fr-ch` in Django, it would give the 'fr_FR' language file.

What about testing if the file exists? If we have 'fr-fr', we first try if 'fr_FR' exists, else we fallback on 'fr'.

I can work on a PR about that.

**Comment by Gagaro** [comment]
By the way, there are 37 language files with a country code and 49 without one.

**Comment by romanvm** [comment]
> It would still not work if we have fr-ch in Django, it would give the 'fr_FR' language file.

I meant a custom mapping that you can set up as you like. But your idea is better.

> By the way, there are 37 language files with a country code and 49 without one.

Yes, that's the problem. 

> What about testing if the file exists? If we have 'fr-fr', we first try if 'fr_FR' exists, else we fallback on 'fr'.

Sounds good. I guess I will add something like this in the next version.

**Comment by romanvm** [comment]
Thanks! I have released v.1.3.1 with this and other improvements, including upgraded TinyMCE 4.

**Comment by Gagaro** [comment]
Thanks for the fast release :+1:
