### ISSUE TITLE
Plans for TinyMCE 5 ?

### ISSUE THREAD

**Issue by merwok** [romanvm/django-tinymce4-lite#52]
Question is in the title :)

**Comment by romanvm** [comment]
Currently there are no concrete plans. When and **if** it happens, it will be in a separate project.

**Comment by merwok** [comment]
Will you wait for django-tinymce5 to appear before creating a -lite version?

**Comment by romanvm** [comment]
Why? It would be good if someone creates functional and well-maintained package for TinyMCE 5. At the moment of creating this project there wasn't such package for TinyMCE 4 and the original project had its problems.

**Comment by merwok** [comment]
I’m just asking to get a sense of where this project will go.

**Comment by romanvm** [comment]
I'm going to support Python/Django part, at least in terms of version compatibility and bug fixing, in the near future. As for JavaScript TinyMCE part, the project uses the latest available version of TinyMCE 4.x and it's still a fully functional rich text editor with many features.

**Comment by merwok** [comment]
OK that answers my question.  Thanks!
